### ISSUE TITLE
Remove Craft.Net dll and add a submodule instead

### ISSUE THREAD

**Issue by pdelvo** [ddevault/PartyCraft#1]
Why don't you use a submodule instead of adding the compiled library of Craft.Net?

This has multiple advantages
- You can view the source code when you work on PartyCraft, and even debug through it.
- You can make changes to the submodule, committing to it, and pulling it to your main project. 
- You can update a submodule very easy. It is very easy to test Partycraft on different Craft.Net Versions

So I think you really should change that

**Comment by ddevault** [comment]
I know very little about how submodules work. Pull request?
