### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by NiLSPACE** [ddevault/PartyCraft#12]
When i try to compile PartyCraft i get 3 warnings and 6 errors. i use this .bat file to compile PartyCraft: 

> git clone --recursive https://github.com/SirCmpwn/PartyCraft.git
> cd PartyCraft
> c:\Windows\Microsoft.net\Framework\v4.0.30319\msbuild /p:Configuration=Release
> pause

I get this:
Microsoft (R) Build Engine version 4.0.30319.17929
[Microsoft .NET Framework, version 4.0.30319.18010]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 25-5-2013 17:32:24.
Project "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Mixed Platforms".
G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln.metaproj : error MSB3202: The project file "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft..\Craft.Net\Craft.Net\Craft.Net.csproj" was not found. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln]
G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln.metaproj : error MSB3202: The project file "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft..\Craft.Net\Craft.Net.Data\Craft.Net.Data.csproj" was not found. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln]
G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln.metaproj : error MSB3202: The project file "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft..\Craft.Net\Craft.Net.Server\Craft.Net.Server.csproj" was not found. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln]
G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln.metaproj : error MSB3202: The project file "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft..\Craft.Net\externals\fNbt\fNbt\fNbt.csproj" was not found. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln]
Project "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln" (1) is building "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft\PartyCraft.csproj" (2) on node 1 (default targets).
Project "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft\PartyCraft.csproj" (2) is building "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj" (3) on node 1 (default targets).
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1395,5): warning : The referenced project '....\Craft.Net\Craft.Net.Data\Craft.Net.Data.csproj' does not exist. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1395,5): warning : The referenced project '....\Craft.Net\Craft.Net.Server\Craft.Net.Server.csproj' does not exist. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1395,5): warning : The referenced project '....\Craft.Net\Craft.Net\Craft.Net.csproj' does not exist. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Xml.Linq.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\PartyCraft.API.dll /target:library /utf8output Plugin.cs IServer.cs ISettingsProvider.cs Properties\AssemblyInfo.cs "C:\Users\niels\AppData\Local\Temp.NETFramework,Version=v4.0.AssemblyAttributes.cs"
IServer.cs(1,7): error CS0246: The type or namespace name 'Craft' could not be found (are you missing a using directive or an assembly reference?) [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]
IServer.cs(12,9): error CS0246: The type or namespace name 'MinecraftServer' could not be found (are you missing a using directive or an assembly reference?) [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]
Done Building Project "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj" (default targets) -- FAILED.
Done Building Project "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft\PartyCraft.csproj" (default targets) -- FAILED.
Done Building Project "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln" (default targets) -- FAILED.

Build FAILED.

"G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln" (default target) (1) ->
"G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft\PartyCraft.csproj" (default target) (2) ->
"G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj" (default target) (3) ->
(ResolveProjectReferences target) -> 
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1395,5): warning : The referenced project '....\Craft.Net\Craft.Net.Data\Craft.Net.Data.csproj' does not exist. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1395,5): warning : The referenced project '....\Craft.Net\Craft.Net.Server\Craft.Net.Server.csproj' does not exist. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1395,5): warning : The referenced project '....\Craft.Net\Craft.Net\Craft.Net.csproj' does not exist. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]

"G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln" (default target) (1) ->
(Build target) -> 
  G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln.metaproj : error MSB3202: The project file "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft..\Craft.Net\Craft.Net\Craft.Net.csproj" was not found. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln]
  G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln.metaproj : error MSB3202: The project file "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft..\Craft.Net\Craft.Net.Data\Craft.Net.Data.csproj" was not found. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln]
  G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln.metaproj : error MSB3202: The project file "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft..\Craft.Net\Craft.Net.Server\Craft.Net.Server.csproj" was not found. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln]
  G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln.metaproj : error MSB3202: The project file "G:\Minecraft Custom\PartyCraft\Batch\PartyCraft..\Craft.Net\externals\fNbt\fNbt\fNbt.csproj" was not found. [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln]

"G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.sln" (default target) (1) ->
"G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft\PartyCraft.csproj" (default target) (2) ->
"G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj" (default target) (3) ->
(CoreCompile target) -> 
  IServer.cs(1,7): error CS0246: The type or namespace name 'Craft' could not be found (are you missing a using directive or an assembly reference?) [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]
  IServer.cs(12,9): error CS0246: The type or namespace name 'MinecraftServer' could not be found (are you missing a using directive or an assembly reference?) [G:\Minecraft Custom\PartyCraft\Batch\PartyCraft\PartyCraft.API\PartyCraft.API.csproj]

```
3 Warning(s)
6 Error(s)
```

Time Elapsed 00:00:00.40

**Comment by pdelvo** [comment]
Make sure you have cloned the submodules too. The easy way:
Clone the repository with 

git clone --recursive git://github.com/SirCmpwn/PartyCraft.git

And git will clone submodules and submodules of submodules ;)

**Comment by NiLSPACE** [comment]
Thats the problem. as you can see on top of this post i used --recursive and it didn't work ;(

**Comment by ddevault** [comment]
Several problems here:
1. You're using a batch script (why?)
2. You're using git from the Windows command line
3. You re-clone the repository every time you want to compile
4. You don't add msbuild to your path, you invoke it manually

Just clone it manually from git, then build it with Visual Studio or something. Follow [the instructions](https://github.com/SirCmpwn/Craft.Net#building-from-source) for Craft.Net, and just use a different repository URL.

Closing this as a non-issue.

**Comment by NiLSPACE** [comment]
1. Becouse i can have it update and then recompile it so i have the latest version.
2. Is there another way?
3. Becouse i can have it update and then recompile it so i have the latest version..
4. if i just use msbuild.exe it says 'msbuild.exe' is not recognized as an internal or external command, operable program or batch file.

**Comment by ddevault** [comment]
1. You're not **updating** it, you're **recloning** it. You can update with `git pull origin master` after the initial clone
2. Yes, git bash
3. See 1
4. You need to add it to your path, of course. This is detailed in the instructions in the link I provided.

**Comment by DinisCruz** [comment]
This is the same error as described here: https://github.com/SirCmpwn/PartyCraft/issues/11

**Comment by ddevault** [comment]
No, it's not.
