### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by fstubner** [ddevault/PartyCraft#18]
Hi there, I was really interested in hearing that there was a C# based Minecraft server software and I wanted to give it a try, unfortunately I am having trouble actually getting anything to work. 

I have downloaded the zip and also downloaded the fNBT library, added all projects to Visual Studio but there are a number of errors created and even after debugging it I wasn't able to get a completed build. 

"Simply run PartyCraft.exe from the command line (Linux/Mac: "mono PartyCraft.exe") to start the server."

Is there an executable file available that I'm missing? It would be great to have a project that I can create a build from since that would allow me to add my own customisations etc. 

Let me know if I missed something or if you have any suggestions.

**Comment by ddevault** [comment]
PartyCraft and Craft.Net are both abandoned in favor of [TrueCraft](https://github.com/SirCmpwn/TrueCraft).

**Comment by fstubner** [comment]
Oh, that's a shame, I was really interested in the C# server, wanted to
create a Server GUI for it :/ Do you know of any other C# based minecraft
servers?

**Comment by ddevault** [comment]
I just linked you to one, dude.

**Comment by Daevil** [comment]
Oh sorry my bad, completely missed that on my read through ^.^ Also,
stumbled over something cool today while doing some research at work
http://www.syncfusion.com/products/communitylicense

I am not affiliated with them but their Winforms are great, had a play
around with them today and they are really customisable :D

**Comment by ddevault** [comment]
Are you seriously shilling syncfusion in a Github issue?

**Comment by fstubner** [comment]
I am not very familiar with Github so not sure what you are referring to :/
